plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version + "-" + project.minecraft_version
group = project.maven_group

base {
    archivesName = project.archives_name
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modCompileOnly "me.lucko:fabric-permissions-api:0.3.1"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mod_id', project.mod_id
    inputs.property 'minecraft_version', project.minecraft_version
    inputs.property 'mod_name', project.mod_name
    inputs.property 'mod_description', project.mod_description
    inputs.property 'mod_authors', project.mod_authors
    inputs.property 'mod_license', project.mod_license
    inputs.property 'mod_sources', project.mod_sources
    inputs.property 'mod_issue_tracker', project.mod_issue_tracker
    inputs.property 'fabric_loader_version', project.fabric_loader_version
    inputs.property 'minimum_minecraft_version', project.minimum_minecraft_version

    def majorMinecraftVersion
    if (project.minimum_minecraft_version != "0") {
        println("Using minimum Minecraft version: ${project.minimum_minecraft_version}")
        majorMinecraftVersion = project.minimum_minecraft_version
    } else {
        majorMinecraftVersion = project.minecraft_version.replaceAll(/(\d+\.\d+)\..*/, '$1')
        println("Using Minecraft version: $majorMinecraftVersion")
    }

    filesMatching('fabric.mod.json') {
        expand(
                version: project.version,
                mod_id: project.mod_id,
                mod_name: project.mod_name,
                mod_description: project.mod_description,
                mod_authors: project.mod_authors.split(',').collect { it.trim() },
                mod_license: project.mod_license,
                mod_sources: project.mod_sources,
                mod_issue_tracker: project.mod_issue_tracker,
                minecraft_version: majorMinecraftVersion,
                fabric_loader_version: project.fabric_loader_version
        )
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_name}" }
    }
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
    }
}

configurations.all {
    resolutionStrategy {
        force("net.fabricmc:fabric-loader:$fabric_loader_version")
    }
}