# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.2
yarn_mappings=1.21.2+build.1
# Mod Properties
mod_version=1.5.2
maven_group=vt
archives_name = ICL
mod_id = icl
mod_name = ICL
mod_description = Designed to improve server performance by periodically removing items from the ground.
mod_authors = VeiTr
mod_license = MIT
mod_sources = https://github.com/VeiTrr/ItemClearLag-ICL
mod_issue_tracker = https://github.com/VeiTrr/ItemClearLag-ICL/issues
# Specify the minimum Minecraft version required to run the mod.
# Else, leave it as 0, and it will default to the major version of the Minecraft version specified above. 1.21.1 -> 1.21
minimum_minecraft_version = 0

# Dependencies
fabric_loader_version = 0.16.7
fabric_api_version = 0.106.1+1.21.2